[package]
name = "blockto_sui"
version = "0.0.1"
published-at = "0x2"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
blockto_sui = "0x0"
sui =  "0x2"
